### ISSUE TITLE
[S1-PBI8] Login Telutizen

### ISSUE THREAD

**Issue by mhyubr** [SI-RPL-2023/SI4401_KEL225_UKMFun#1]
Sebagai Telutizen, saya ingin dapat melakukan login ke dalam aplikasi agar saya bisa mengakses fitur-fitur yang memerlukan autentikasi.

![Image](https://user-images.githubusercontent.com/115601576/230807414-ec432446-38d4-487f-a715-62fbe3e15ec8.jpeg)

**Comment by Dimaslevi** [comment]
![Image](https://user-images.githubusercontent.com/115601576/229391836-2d8a1e01-ebe2-4b02-8421-95ca8cbfcde6.jpeg)

**Comment by tienfkusumasari** [comment]
UX dessing taro di atas jangan di comment. issue close
