### ISSUE TITLE
[S2-PBI17] Detail Informasi UKM

### ISSUE THREAD

**Issue by mhyubr** [SI-RPL-2023/SI4401_KEL225_UKMFun#17]
**[S2-PBI17] Detail Informasi UKM**

**DESKRPSI:**
Sebagai Telutizen, saya ingin dapat melihat detail informasi kegiatan UKM agar saya dapat mengetahui informasi yang lebih lengkap tentang kegiatan tersebut.

**NOTE:**
-	Dikerjakan setelah Menu Edit UKM oleh admin UKM telah selesai. 
-	Backlog ini terhubung dengan database pada table content.

**ACTIVITY DIAGRAM:**
![Image](https://user-images.githubusercontent.com/82822513/232553048-1f996f81-9266-4e66-a7e2-9a21866baad9.jpg)

**USE CASE DIAGRAM:**
![Image](https://user-images.githubusercontent.com/82822513/232355410-ddc4223f-e319-4fb0-a256-7c0a5a8177c3.png)

**DESAIN FIGMA:**
![Image](https://user-images.githubusercontent.com/82822513/232356361-6d41a3a3-50e7-4815-be98-78e880c440b8.jpg)

**Comment by tienfkusumasari** [comment]
done (sprint 2 minggu k 11) 
catatan = pembagian issue kurang seragan. terlalu kecil utk issue 17
