### ISSUE TITLE
[S1-PBI9] Logout Telutizen

### ISSUE THREAD

**Issue by mhyubr** [SI-RPL-2023/SI4401_KEL225_UKMFun#2]
Sebagai Telutizen, saya ingin dapat melakukan logout dari aplikasi agar saya bisa keluar dari akun saya dan mencegah akses tidak sah

Link Figma : https://www.figma.com/file/AvS5GUlMhdHZwuU1FOUoGB/UKM-FunRPL?node-id=0%3A1&t=9Hr3bLkzAzt5fiN4-1

![Image](https://user-images.githubusercontent.com/115547842/232321833-9adb4104-a8fe-45db-b9ef-bb2df740189a.jpeg)

**Comment by itsvannnss** [comment]
.
