### ISSUE TITLE
[S3-PBI23] Mendaftar kegiatan UKM

### ISSUE THREAD

**Issue by mhyubr** [SI-RPL-2023/SI4401_KEL225_UKMFun#23]
[S2-PBI23] Mendaftar kegiatan UKM

ROLE :
Admin UKM 

DESKRPSI :
Sebagai Telutizen, saya ingin dapat mendaftar untuk mengikuti kegiatan yang diadakan oleh UKM agar saya
dapat mengikuti kegiatan tersebut dan mendapatkan manfaat dari kegiatan tersebut.

NOTE : 
- Dikerjakan setelah backlog "Detail informasi kegiatan UKM" telah selesai
- Terhubung dengan database pada "table Event"

DESAIN FIGMA :
![Image](https://github.com/SI-RPL-2023/SI4401_KEL225_UKMFun/assets/82822513/b7706725-d0cb-4245-80d5-33096ca72a9b)

USE CASE DIAGRAM :
![Image](https://github.com/SI-RPL-2023/SI4401_KEL225_UKMFun/assets/82822513/bfac8b74-c6d7-45cf-89da-030eddadc1fd)

ACTIVITY DIAGRAM :
![Image](https://github.com/SI-RPL-2023/SI4401_KEL225_UKMFun/assets/82822513/75e179d7-b262-4fdc-8890-eb8c59c316c2)

SCENARIO TESTING :
1. User membuka halaman login UKM Fun
2. User melakukan login sebagai Mahasiswa
3. User membuka halaman event dengan menekan button "Event" pada navbar
4. User memilih salah satu event yang terdapat pada list event
5. User membuka detail informasi mengenai Event
6. User menekan button "Daftar Kegiatan" pada halaman tersebut

**Comment by tienfkusumasari** [comment]
belum selesaiSP3)

**Comment by tienfkusumasari** [comment]
done + attomatic testing
