### ISSUE TITLE
[S0-PBI1] Proses Bisnis Targeting Pendaftaran UKM

### ISSUE THREAD

**Issue by mhyubr** [SI-RPL-2023/SI4401_KEL225_UKMFun#24]
[S0-PBI1] Proses Bisnis Targetting Pendafataran UKM #24 

Sebagai admin, saya ingin membuat proses bisnis  targeting agar dapat menggambarkan keadaan proses bisnis pendaftran UKM yang mana menggambarkan usulan proses bisnis yang akan dibuat

![Image](https://user-images.githubusercontent.com/115547842/230802544-03b73e76-dde3-48f9-a24c-b8c463bd619a.png)

**Comment by itsvannnss** [comment]
.

**Comment by tienfkusumasari** [comment]
kasih insruksi detail untuk isseu dan penejelasan detail
