### ISSUE TITLE
[S0-PBI2] Proses Bisnis Targeting Event UKM

### ISSUE THREAD

**Issue by mhyubr** [SI-RPL-2023/SI4401_KEL225_UKMFun#25]
Proses Bisnis Pendaftaran Event UKM

**Comment by itsvannnss** [comment]
![Image](https://user-images.githubusercontent.com/115547842/230801010-49614aba-8dc8-4fc7-91fc-1fabc1ef8ba2.png)

**Comment by tienfkusumasari** [comment]
tidak bisa dijadikan issue individu
