### ISSUE TITLE
[S0-PBI4] Class Digram UKM Fun

### ISSUE THREAD

**Issue by mhyubr** [SI-RPL-2023/SI4401_KEL225_UKMFun#28]
Class Diagram UKM Fun

**Comment by itsvannnss** [comment]
Class Diagram


![Image](https://user-images.githubusercontent.com/115637789/230805056-fae6d8bc-134e-4331-ba9e-a4914086d80d.png)

**Comment by Habibiakmal** [comment]
/

**Comment by tienfkusumasari** [comment]
pembuatan issue kurang detail dan harus di taro di body bukan di comen .Bentuk issue adalah task atau instruksi
