### ISSUE TITLE
[S0-PBI5] ERD Diagram UKM Fun

### ISSUE THREAD

**Issue by mhyubr** [SI-RPL-2023/SI4401_KEL225_UKMFun#29]
[[S1-PBI6] ERD Diagram UKM Fun](https://github.com/SI-RPL-2023/SI4401_KEL225_UKMFun/issues/29)

![Image](https://user-images.githubusercontent.com/82822513/230802430-3331ecc2-5ddf-475f-9242-9f03b2c8f02b.jpg)

ERD diagram di atas memiliki 4 entity yaitu diantaranya: 

1. Users, digunakan untuk menyimpan data pengguna aplikasi baik dari Telutizen maupun Admin UKM. Entity users memiliki atribut yaitu sebagai berikut:

- id_user bigint(20) (Primary Key) (AI)
- nama varchar(255)
- nim int(11)
- jurusan varchar(255)
- jk varchar(255)
- email varchar(255)
- password varchar(255)
- role varchar(255)
 
2. Contents, digunakan untuk menyimpan data content halaman dari Admin UKM. Entity contents memiliki atribut yaitu sebagai berikut:

- id_content bigint(20) (Primary Key) (AI)
- id_ukm int(11)
- nama_ukm varchar(255)
- deskripsi varchar(5000)
- jumbotron varchar(255)
- visi varchar(5000)
- misi varchar(5000)
- galeri varchar(255)

3. Pendaftarans, digunakan untuk menyimpan data pendaftaran UKM antara TelutIzen dengan Admin UKM. Entity pendaftaran memiliki atribut yaitu sebagai berikut:

- id_pendaftaran bigint(20) (Primary Key) (AI)
- id_mahasiswa int(11)
- id_ukm int(11)
- nama_ukm varchar(50)
- nama varchar(255)
- nim int(11)
- jurusan varchar(255)
- jk varchar(255)
- alamat varchar(2000)
- email varchar(255)
- no_hp int(11)
- ksm varchar(255)
- khs varchar(255)
- cv varchar(255)
- status varchar(255)

4. Events, digunakan untuk menyimpan data kegiatan UKM untuk selanjutnya dapat dilakukan pendaftaran oleh Telutizen. Entity Events memiliki atribut yaitu sebagai berikut:

- id_event bigint(20) (Primary Key) (AI)
- id_ukm int(11)
- nama_ukm varchar(255)
- nama_event varchar(255)
- poster varchar(255)
- tanggal date
- deskripsi varchar(5000)
- link varchar(5000)

**Comment by itsvannnss** [comment]
-

**Comment by mhyubr** [comment]
![Image](https://user-images.githubusercontent.com/82822513/230801393-ed18ffa8-a962-4e82-9d43-84aa0021746f.jpg)

**Comment by tienfkusumasari** [comment]
lengkapi dengan tipe data

**Comment by tienfkusumasari** [comment]
close
