### ISSUE TITLE
[S1-PBI7] Migrate Database

### ISSUE THREAD

**Issue by mhyubr** [SI-RPL-2023/SI4401_KEL225_UKMFun#30]
[[S1-PBI8] Migrate Database](https://github.com/SI-RPL-2023/SI4401_KEL225_UKMFun/issues/30)

Code:
![Image](https://user-images.githubusercontent.com/82822513/230803049-b024eb81-f6dd-432b-b589-717c0a00b214.png)

SQL Database:
![Image](https://user-images.githubusercontent.com/82822513/230803061-b4867b75-2599-486b-9f11-718232f01a04.png)

**Comment by mhyubr** [comment]
![Image](https://user-images.githubusercontent.com/82822513/230801475-89a8d8e3-dab9-4d1e-9b6b-a3c07f3dd1bd.png)

**Comment by mhyubr** [comment]
![Image](https://user-images.githubusercontent.com/82822513/230801530-d542ded3-b2ac-467e-8f8b-b72b5423ec7a.png)

**Comment by tienfkusumasari** [comment]
commit semua tabel yagn telah di buat migrate nya (4 tabel)

**Comment by tienfkusumasari** [comment]
close
