### ISSUE TITLE
[S0-PBI6] Activity Diagram

### ISSUE THREAD

**Issue by mhyubr** [SI-RPL-2023/SI4401_KEL225_UKMFun#31]
[S1-PB17] Activity Diagram #31

Sebagai admin, keinginan saya adalah untuk membuat diagram aktivitas yang dapat menggambarkan aktivitas dan alur kerja dari proses bisnis targeting yang sudah dibuat sebelumnya.

Link Activity Diagram : https://docs.google.com/document/d/1vK3uWWpCW4QZHKUSrUzsK7wHZkQJU3TTbsxY01Hq17M/edit?usp=sharing

![Image](https://user-images.githubusercontent.com/115547842/232321549-1b1c2623-57e2-4c87-9e02-32d9e0cf4487.png)

**Comment by itsvannnss** [comment]
.
