### ISSUE TITLE
[S1-PBI11] Logout Admin UKM

### ISSUE THREAD

**Issue by mhyubr** [SI-RPL-2023/SI4401_KEL225_UKMFun#4]
Sebagai Admin UKM, saya ingin dapat melakukan logout dari aplikasi agar saya bisa keluar dari akun saya dan mencegah akses tidak sah.

**Comment by mhyubr** [comment]
![Image](https://user-images.githubusercontent.com/82822513/229391547-6a7658ba-42ff-445c-882b-dc3c4e8ecdd3.png)

**Comment by tienfkusumasari** [comment]
ok
