### ISSUE TITLE
[S3-PBI26] Menambahkan List User

### ISSUE THREAD

**Issue by mhyubr** [SI-RPL-2023/SI4401_KEL225_UKMFun#50]
[S2-PBI26] Menambahkan List User

ROLE : 
General Admin

DESKRPSI :
Sebagai General Admin, saya ingin dapat menambahkan daftar pengguna baru ke dalam sistem agar dapat dikelola oleh General Admin dengan mudah dan efisien.

NOTE : 
- Backlog ini dibuat setelah fitur login General Admin selesai
- Backlog ini terhubung dengan database pada table User

DESAIN FIGMA :
![Image](https://github.com/SI-RPL-2023/SI4401_KEL225_UKMFun/assets/82822513/0f181b14-4a2b-4c5f-8483-36e1b125edcf)

USE CASE DIAGRAM :
![Image](https://github.com/SI-RPL-2023/SI4401_KEL225_UKMFun/assets/82822513/9407ff16-a046-4989-ae4b-c634c1255a7d)

ACTIVITY DIAGRAM :
![Image](https://github.com/SI-RPL-2023/SI4401_KEL225_UKMFun/assets/82822513/b37ea3be-dd8d-4a10-8359-13bf000c2791)

SCENARIO TESTING :

1. User membuka halaman login UKM Fun
2. User melakukan login sebagai General Admin
3. User membuka halaman user pada button "User" di navbar
4. User mendownload Format excel dengan menekan button "Download Format"
5. User mengisi list user beserta
6. User mengupload list user baik mahasiswa maupun UKM
7. User menekan button "Tambahkan User +"
8. User dapat melihat tabel user yang telah ditambahkan

**Comment by tienfkusumasari** [comment]
close (automatic testing nya udah )
