### ISSUE TITLE
[S3-PBI22] Detail informasi kegiatan UKM

### ISSUE THREAD

**Issue by maysbkti11** [SI-RPL-2023/SI4401_KEL225_UKMFun#61]
ROLE: Telutizen

DESKRPSI: Sebagai Telutizen, saya ingin dapat melihat detail informasi UKM agar saya dapat mengetahui informasi yang lebih lengkap tentang UKM tersebut.

NOTE:

ACTIVITY DIAGRAM (yang ada, cek di proposal update terbaru):

DESAIN FIGMA (Jika Ada):

![Image](https://github.com/SI-RPL-2023/SI4401_KEL225_UKMFun/assets/83778553/1ea378cb-e437-49bc-926c-e5f66e8af86c)

**Comment by tienfkusumasari** [comment]
done (SP3). automatic testing belum

**Comment by tienfkusumasari** [comment]
automatic testng
